export const menuitems=[
    {
        title:'Home',
        url:'#',
        cName:'nav-links',
        route:'home'
    },
    {
        title:'Services',
        url:'#',
        cName:'nav-links',
        route:'services'
    },
    {
        title:'Contact',
        url:'#',
        cName:'nav-links',
        route:'footer'
    },
    {
        title:'About',
        url:'#',
        cName:'nav-links',
        route:'about'
    },
    {
        title:'Register',
        url:'#',
        cName:'nav-sigin',
        route:'register'
    }
    ];